@startuml

class User{
    user_id（用户id）
    name（用户真实姓名）
    github_account（github账号）
    update_date（用户github修改日期）
    password（用户密码）
    disable（用户是否禁用）
}

class Teacher extends User{
    teacher_id(老师工号)
    department(老师所属部门)
}

class Student extends User{
    student_id（学号）
    class（班级）
    web_sum（网站是否正确）
}

class BaseCourse{
    base_course_id（课程id）
    name（课程名称）
    academy（开课学院）
}
class SelectedCourse extends BaseCourse{
    selected_course_id（选课id）
    semester（开课学期）
    teacher_id（开课老师id）
    student_id（选课学生id）
}

class Test{
    test_id（实验id）
    name（实验名称）
    selected_course_id（开课id）
    weight（实验评分权重）
    update_date（修改日期）
}

class TestItem{
    test_item_id（实验评分项id）
    test_id（实验id）
    name（实验评分项名称）
    description（描述或说明）
    weight（评分项权重）
}

class TotalGrade{
    total_grade_id（实验总分id）
    test_id（实验id）
    result（总分）

}
class ItemGrade{
    item_grade_id（评分项分数id）
    student_id（学号）
    test_item_id（评分项id）
    result（分数）
    memo（评价）
    update_date（评改日期）
}

Test "1"--"n" TestItem
SelectedCourse "1" - "n" Test
ItemGrade "1"-"1" TestItem
ItemGrade "n"-"1" Student
ItemGrade "n"-"1" TotalGrade
TotalGrade "1"-"1" Test
@enduml