@startuml
title 查询借阅情况和续借
actor Reader as r
participant System as s
database Database as d
r -> s:请求登录
s -> d:查询
alt 存在数据
    d --> s:返回数据
    alt 认证成功
        s --> r:登录成功
        r -> s:请求进入个人页面
        s -> d:查询用户数据
        d --> s:返回用户数据
        s --> r:返回个人页面
        r -> s:查询借阅信息
        s -> d:查询数据
        alt 存在借阅数据
            d --> s:返回数据
            s --> r:返回借阅信息
            r -> s:请求续借
            s -> d:查询是否满足续借条件
            d --> s:返回数据
            alt 满足
                s -> d:写入续借信息
                d -->s:写入成功
                s --> r:续借成功
            else 不满足
                s --> r:续借失败
            end
        else 不存在借阅信息
            d --> s:返回不存在数据
            s --> r:不存在借阅信息
        end
    else 认证失败
        s --> r:登录失败
        note right of r
            1.密码错误
            2.登录限制
        end note
    end
else 不存在数据
    d --> s:不存在数据
    s --> r:登录失败
    note right of r
        1.用户不存在
    end note
end

@enduml