@startuml
start
:图书管理员登录;
fork
:新增图书信息;
:点击添加;
:录入图书信息;
:点击提交;
if(系统检查图书重复?) then(否)
    :添加成功>
    else (是)
    :该图书已存在>
    endif
fork again
:修改图书信息;
:输入图书编号或书名关键词查询;
:修改除图书编号以外的其他信息;
:点击提交;
:修改成功;
end fork
:流程结束;
end
@enduml